source 'https://rubygems.org'

gem 'rails'
gem 'pg'
gem 'puma'
gem 'jsonapi-resources', '0.8.0.beta2'
gem 'sucker_punch'
gem 'dotenv-rails'
gem 'jwt'

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'spring'
  gem 'database_cleaner'
  gem 'annotate'
end
