source 'https://rubygems.org'

gem 'rails', '>= 5.0.0.beta1', '< 5.1'
gem 'pg', '~> 0.18'
gem 'puma'
gem 'active_model_serializers', '0.10.0.rc3'
gem 'sucker_punch'
gem 'ember-cli-rails'

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'spring'
  gem 'database_cleaner'
end
